name: Validate & Release
on:
  push:
    tags:
      - v*
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: https://npm.pkg.github.com/
          scope: "@mobilelive-inc"
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PUBLISH_TOKEN }}
      - run: npm run check

  publish-npm:
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://npm.pkg.github.com/
        scope: "@mobilelive-inc"
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_PUBLISH_TOKEN }}
